spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db
    username: admin
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
